project_id = "xvwtxobrztdepzxveyrs"

[api]
port = 5656
enabled = true

[functions]
# port = 5656
[functions.generate-campaign-gemini]
enabled = true
verify_jwt = true
import_map = "./functions/generate-campaign-gemini/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-campaign-gemini/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-campaign-gemini/*.html" ]
